[package]
name = "pgx_demo"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg13"]
pg10 = ["pgx/pg10", "pgx-tests/pg10" ]
pg11 = ["pgx/pg11", "pgx-tests/pg11" ]
pg12 = ["pgx/pg12", "pgx-tests/pg12" ]
pg13 = ["pgx/pg13", "pgx-tests/pg13" ]
pg_test = []

[dependencies]
pgx = { git = "https://github.com/hoverbear/pgx", branch = "omni" }
pgx-macros = { git = "https://github.com/hoverbear/pgx", branch = "omni" }

[dev-dependencies]
pgx-tests = { git = "https://github.com/hoverbear/pgx", branch = "omni" }
pgx-utils = { git = "https://github.com/hoverbear/pgx", branch = "omni" }
pgx-pg-sys = { git = "https://github.com/hoverbear/pgx", branch = "omni" }
tempdir = "0.3.7"
once_cell = "1.7.2"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
